version: "3.9"

services:
  db:
    image: ankane/pgvector:latest
    container_name: postgres_pgvector
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tutor_inteligente
      POSTGRES_HOST_AUTH_METHOD: trust # ← Esto evita problemas de autenticación inicial
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tutor_inteligente"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
